apiVersion: 1
datasources:
 - name: InfluxDB
   type: influxdb
   access: proxy
   url: http://localhost:8086
   jsonData:
     version: Flux
     organization: mini_air_quality
     defaultBucket: sensor_data
   secureJsonData:
     token: 6y-fM0HpRAwx1P-fbH_3DaXklPqyFlAzUd58STICzqAlIcOks55jpjhyf6udF-nCykZTLzRMor48r279jfFWWw==
